### ISSUE TITLE
BUG: Images broken on Stage domain

### ISSUE THREAD

**Issue by nc-andreashaller** [Netcentric/cn-website#173] opened 2022-12-02 07:01 UTC
Currently the request 
https://www-stage.netcentric.biz/insights/2022/09/content-at-scale/_jcr_content/responsivecontainergrid/fixed_image.coreimg.720.jpeg/1664278885826.jpeg
sometimes returns 200 sometimes 302 redirecting to https://www.netcentric.biz.

We assume that the redirect is coming from Fastly as it stops if we remove the 404 redirect rule. As the error turns on and off per request we assume that one of the AEM instances is currently not health in some way, this needs to be investigated.

**Comment by EduNCgit** [comment] 2023-01-13 11:08
The issue is still present, opening the link in incognito mode will display the image, and other times opening it normally will display the homepage.

**Comment by NCalexiaeche** [comment] 2023-01-16 14:49
Check Publish instance on AEM on stage

**Comment by alexnerdrumhansen** [comment] 2023-09-28 11:16
Currently giving 404 error since the page is no longer published.
@chriscorr1 , unless we want to republish the page I think we can close this.

**Comment by alexnerdrumhansen** [comment] 2023-10-19 11:15
@nc-andreashaller, it seems the page is no longer published so I'm wondering if we can close this or we publish the page and check again?
Thanks!

**Closed** 2023-10-24 11:16 UTC
Labels: bug

**Comment by nc-andreashaller** [comment] 2023-10-24 15:57
AEM classic is completely phased out from nc.biz in the meantime so this is indeed not valid anymore.
